FROM golang:1.22.0 AS DEV

WORKDIR /backend

# If wait for javaxcript to render the page will be needed, then this should be added back.
# RUN apt-get clean && \
#     rm -rf /var/lib/apt/lists/* && \
#     apt-get update && \
#     apt-get install -y chromium || \
#     apt-get install -y chromium

RUN mkdir /logs

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

ENTRYPOINT /go/bin/CompileDaemon -build="go build -o /cobh ."\
                                 -command="/cobh prepare"\
                                 -pattern="backend/build/+\.*"\
                                 -include="*.js"\
                                 -include="*.jsx"\
                                 -include="*.css"\
                                 -include="*.html"\
                                 -include="*.png"\
                                 -include="*.json"\
                                 -include="*.go"\
                                 -include="*.c"


FROM golang:1.22.0 AS UNIT_TEST

COPY ./backend /backend

WORKDIR /backend
ENV GO111MODULE=on

RUN mkdir logs

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

ENTRYPOINT /go/bin/CompileDaemon -build="go build -o /cobh ."\
                                 -command="go test -v -count=1 -cover -race ./..."\
                                 -pattern="backend/build/+\.*"\
                                 -include="*.js"\
                                 -include="*.jsx"\
                                 -include="*.css"\
                                 -include="*.html"\
                                 -include="*.png"\
                                 -include="*.json"\
                                 -include="*.go"\
                                 -include="*.c"